//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recetas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int Id_Fav { get; set; }
        public int Id_recipe { get; set; }
        public int Id_User { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
