//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recetas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Favorites = new HashSet<Favorite>();
            this.Ingredientes = new HashSet<Ingrediente>();
        }
    
        public int Id_recipe { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Id_Categoria { get; set; }
        public int Id_Ingredientes { get; set; }
        public Nullable<decimal> Calories { get; set; }
        public Nullable<decimal> Fat { get; set; }
        public Nullable<decimal> Carbs { get; set; }
        public Nullable<decimal> Protein { get; set; }
        public Nullable<int> Preptime { get; set; }
        public Nullable<int> Cooktime { get; set; }
        public Nullable<int> ReadyIn { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingrediente> Ingredientes { get; set; }
        public virtual Ingrediente Ingrediente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
